version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    networks:
      - koko

  django:
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000"
    depends_on:
      - db
    networks:
      - koko

  httpnewserver:
    build:
      context: ./nginxconf
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - koko
    depends_on:
      - django

networks:
  koko:


