version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - koko

  django:
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/code
      - static_data:/srv
    ports:
      - "8000"
    depends_on:
      - db
    networks:
      - koko

  httpnewserver:
    build:
      context: ./nginxconf
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - koko
    depends_on:
      - django
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - static_data:/srv:ro

networks:
  koko:

volumes:
  static_data:
  postgres-data:


