version: 2.1

orbs:
  python: circleci/python:3.8

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker

workflows:
  main:
    jobs:
      - build-and-test
