version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container and verify it is working and run tests
          command: |
            set -x
            docker-compose up -d
            docker exec -it project_django_1 /bin/sh -c "python manage.py test"

  push-image:
    machine: true
    steps:
      - checkout
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: docker compose build --rm=false -t us.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push us.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1


workflows:
  test-and-push-image:
    jobs:
      - build-and-test
      - push-image:
          requires:
            - build-and-test
